/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PRINCIPAL;

import javax.swing.JOptionPane;
import Clases.*;
import java.util.HashMap;

/**
 *
 * @author karol
 */
public class frmInicio extends javax.swing.JFrame {
    public static HashMap<String, Usuario> usuarios = new HashMap<>(); 

    private static final String ADMIN_USERNAME = "admin"; // Usuario predeterminado

    private static final String ADMIN_PASSWORD = "admin123";
    private ListaEnlazada listaUsuarios; 
    /**
     * Creates new form frmInicio
     */
    public frmInicio(ListaEnlazada listaUsuarios) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.listaUsuarios = listaUsuarios;
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jlbUsuario = new javax.swing.JTextField();
        jlbContraseña = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcmTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Contraseña:");

        jlbUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlbUsuarioActionPerformed(evt);
            }
        });

        jlbContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tipo de Usuaio:");

        jcmTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcmTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Mesero", "Cocinero", "Bartender" }));
        jcmTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmTipoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Usuario:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setText("Inicio de sesión");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcmTipo, 0, 197, Short.MAX_VALUE)
                            .addComponent(jlbUsuario)
                            .addComponent(jlbContraseña)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButton2)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcmTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlbContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlbUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String usuario = jlbUsuario.getText();
    String contraseña = new String(jlbContraseña.getPassword());
    String tipoEsperado = (String)jcmTipo.getSelectedItem();
    
    // Verifica si el usuario es el administrador
    if (usuario.equals(ADMIN_USERNAME) && contraseña.equals(ADMIN_PASSWORD)) {
        frmMenuPrincipal mi = new frmMenuPrincipal(listaUsuarios);
        mi.setVisible(true);
        JOptionPane.showMessageDialog(null, "¡Bienvenido al sistema " + usuario + "!");
        this.setVisible(false);
    } else {
        // Buscar el usuario en la lista enlazada
        Usuario usuarioRegistrado = listaUsuarios.buscar(usuario);

        if (usuarioRegistrado != null && usuarioRegistrado.getContraseña().equals(contraseña)) {
            // Si el usuario existe, verifica su rol
            
            if (usuarioRegistrado.getTipo().equals(tipoEsperado)) {   
            
            frmMenuPrincipal mi = new frmMenuPrincipal(listaUsuarios);
            
            // Control de roles
            if (usuarioRegistrado.getTipo().equals("Mesero")) {
                mi.Inventario.setVisible(false);
                mi.VentasT.setVisible(false);
                mi.Empleados.setVisible(false);
            } else if (usuarioRegistrado.getTipo().equals("Cocinero")) {
                mi.VentasT.setVisible(false);
                mi.Empleados.setVisible(false);
                mi.Ordenes.setVisible(false);
            } else if (usuarioRegistrado.getTipo().equals("Bartender")) {
                mi.VentasT.setVisible(false);
                mi.Empleados.setVisible(false);
                mi.Ordenes.setVisible(false);
            }
            
            mi.setVisible(true);
            JOptionPane.showMessageDialog(null, "¡Bienvenido al sistema " + usuario + "!");
            this.setVisible(false);
            } else {
            JOptionPane.showMessageDialog(null, "ERROR: Tipo de usuario no permitido para este acceso.", "Error", JOptionPane.ERROR_MESSAGE);
        }
            
        } else {
            JOptionPane.showMessageDialog(null, "ERROR: Verifique los datos!!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jcmTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    ListaEnlazada listaUsuarios = new ListaEnlazada();    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            frmInicio ini = new frmInicio(listaUsuarios);
            ini.setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jcmTipo;
    private javax.swing.JPasswordField jlbContraseña;
    private javax.swing.JTextField jlbUsuario;
    // End of variables declaration//GEN-END:variables
}
