/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PRINCIPAL;

import Clases.Cola;
import Clases.ColaPlatillo;
import Clases.ListaEnlazada;
import Clases.Usuario;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.*;

/**
 *
 * @author karol
 */
public class frmMenuPrincipal extends javax.swing.JFrame implements Runnable {
    String hora, min, seg, ampm;
    Calendar calendario;
    Thread h1;

    private ListaEnlazada listaUsuarios;
    private Cola colaIngredientes;
    private ColaPlatillo colaPlatillos;
    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal(ListaEnlazada listaUsuarios ) {
        initComponents();

        this.listaUsuarios = listaUsuarios;
        this.colaIngredientes = new Cola();
        this.colaPlatillos = new ColaPlatillo();

        h1 = new Thread(this);
        h1.start();

        cargarDatos();
        
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            eliminarDatos();
        }));
    }


    @Override
    public void run() {
        
        Thread ct = Thread.currentThread();

        while (ct == h1) {
            calcula();
            lblReloj.setText(hora + ":" + min + ":" + seg + " " + ampm);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException error) {
            }
        }


    }

    private void guardarDatos() {
        try {
            // Serializar las colas de ingredientes y platillos
            ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream("almacen.dat"));
            out.writeObject(colaIngredientes);
            out.writeObject(colaPlatillos);
            out.close();
            System.out.println("Datos guardados con éxito.");
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println("Error al guardar los datos.");
        }
    }
    
    private void cargarDatos() {
        try {
            // Deserializar las colas de ingredientes y platillos
            ObjectInputStream in = new ObjectInputStream(new FileInputStream("almacen.dat"));
            colaIngredientes = (Cola) in.readObject();
            colaPlatillos = (ColaPlatillo) in.readObject();
            in.close();
            System.out.println("Datos cargados con éxito.");
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
            System.out.println("Error al cargar los datos.");
        }
    }
    
    private void eliminarDatos() {
        File archivo = new File("almacen.dat");
        if (archivo.exists()) {
            if (archivo.delete()) {
                System.out.println("Archivo almacen.dat eliminado con éxito.");
            } else {
                System.out.println("No se pudo eliminar el archivo almacen.dat.");
            }
        }
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmcMenu = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        lblReloj = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Empleados = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        Inventario = new javax.swing.JMenu();
        jmiInventarioRegistrar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmiInventarioMostrar = new javax.swing.JMenuItem();
        Platillos = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        Ordenes = new javax.swing.JMenu();
        VentasT = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cerrar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblReloj.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblReloj.setForeground(new java.awt.Color(255, 255, 255));

        jmcMenu.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jmcMenu.setLayer(lblReloj, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jmcMenuLayout = new javax.swing.GroupLayout(jmcMenu);
        jmcMenu.setLayout(jmcMenuLayout);
        jmcMenuLayout.setHorizontalGroup(
            jmcMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jmcMenuLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 654, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );
        jmcMenuLayout.setVerticalGroup(
            jmcMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jmcMenuLayout.createSequentialGroup()
                .addContainerGap(663, Short.MAX_VALUE)
                .addGroup(jmcMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jmcMenuLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jmcMenuLayout.createSequentialGroup()
                        .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        Empleados.setText("Empleados");

        jMenuItem1.setText("Registro");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Empleados.add(jMenuItem1);
        Empleados.add(jSeparator1);

        jMenuItem2.setText("Mostrar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Empleados.add(jMenuItem2);

        jMenuBar2.add(Empleados);

        Inventario.setText("Inventario");

        jmiInventarioRegistrar.setText("Registrar");
        jmiInventarioRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInventarioRegistrarActionPerformed(evt);
            }
        });
        Inventario.add(jmiInventarioRegistrar);
        Inventario.add(jSeparator2);

        jmiInventarioMostrar.setText("Mostrar");
        jmiInventarioMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInventarioMostrarActionPerformed(evt);
            }
        });
        Inventario.add(jmiInventarioMostrar);

        jMenuBar2.add(Inventario);

        Platillos.setText("Platillos");

        jMenuItem3.setText("Registrar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Platillos.add(jMenuItem3);
        Platillos.add(jSeparator3);

        jMenuItem4.setText("Mostrar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Platillos.add(jMenuItem4);

        jMenuBar2.add(Platillos);

        Ordenes.setText("Ordenes");
        jMenuBar2.add(Ordenes);

        VentasT.setText("Ventas T");
        jMenuBar2.add(VentasT);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jmcMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jmcMenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       guardarDatos();  // Guardar los datos antes de cerrar sesión

        // Cerrar el formulario actual y abrir el de inicio
        this.setVisible(false);
        frmInicio ini = new frmInicio(listaUsuarios);
        ini.setVisible(true);
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    frmRegistroEmpleados em = new frmRegistroEmpleados(listaUsuarios);
    jmcMenu.add(em);
    em.setVisible(true);    
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       frmMEmpleados em = new frmMEmpleados(listaUsuarios);
       jmcMenu.add(em);
       em.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmiInventarioMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInventarioMostrarActionPerformed
         frmInventarioMostrar em = new frmInventarioMostrar(colaIngredientes);
         jmcMenu.add(em);
         em.setVisible(true);
    }//GEN-LAST:event_jmiInventarioMostrarActionPerformed

    private void jmiInventarioRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInventarioRegistrarActionPerformed
         frmInventarioRegistro em = new frmInventarioRegistro(colaIngredientes);
         jmcMenu.add(em);
         em.setVisible(true);
    }//GEN-LAST:event_jmiInventarioRegistrarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        frmPlatilloRegistrar em = new frmPlatilloRegistrar(colaPlatillos);
        jmcMenu.add(em);
        em.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        frmPlatilloMostrar em = new frmPlatilloMostrar(colaPlatillos);
        jmcMenu.add(em);
        em.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenu Empleados;
    public static javax.swing.JMenu Inventario;
    public static javax.swing.JMenu Ordenes;
    public static javax.swing.JMenu Platillos;
    public static javax.swing.JMenu VentasT;
    private javax.swing.JButton jButton1;
    public static javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    public static javax.swing.JDesktopPane jmcMenu;
    private javax.swing.JMenuItem jmiInventarioMostrar;
    private javax.swing.JMenuItem jmiInventarioRegistrar;
    private javax.swing.JLabel lblReloj;
    // End of variables declaration//GEN-END:variables

    

    private void calcula() {
        Calendar calendario = new GregorianCalendar();
        Date fechaHoraActual = new Date();
        calendario.setTime(fechaHoraActual);
        ampm = calendario.get(Calendar.AM_PM) == Calendar.AM ? "AM" : "PM";

        // Calcular la hora en formato de 12 horas
        if (ampm.equals("PM")) {
            int h = calendario.get(Calendar.HOUR_OF_DAY) - 12;
            if (h == 0) {
                hora = "12"; // Caso especial para la medianoche
            } else {
                hora = h > 9 ? "" + h : "0" + h; // Formato de hora (sin el 0 inicial)
            }
        } else {
            hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        }

        min = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        seg = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }
}
