/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package PRINCIPAL;

import Clases.ColaPlatillo;
import Clases.Platillo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Clases.NodoPlatillo;

/**
 *
 * @author Danyphantom
 */
public class frmPlatilloMostrar extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmPlatilloMostrar
     */
    private ColaPlatillo colaPlatillos;

    public frmPlatilloMostrar(ColaPlatillo colaPlatillos) {
        initComponents();
        this.colaPlatillos = colaPlatillos;
        mostrarPlatillos(); 
    }   

     private void mostrarPlatillos() {
        DefaultTableModel modelo = (DefaultTableModel) jTablePlatillo.getModel();
        modelo.setRowCount(0);  // Limpia la tabla antes de mostrar los datos

        if (colaPlatillos.estaVacia()) {
            JOptionPane.showMessageDialog(this, "No hay platillos en la cola.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;  // Si la cola está vacía, salimos del método
        }

        NodoPlatillo actual = colaPlatillos.getFrente();
        while (actual != null) {
            Platillo platillo = actual.getPlatillo();
            modelo.addRow(new Object[]{
                platillo.getNombre(),
                platillo.getCategoria(),
                platillo.getPrecio(),
                platillo.getHorarioDisponible(),
                platillo.isEstaEnStock(),
                platillo.getRutaImagen()
            });
            actual = actual.getSiguiente();  // Avanzar al siguiente nodo
        }
    }

     
     

    public void actualizarVista() {
        mostrarPlatillos(); 
    }
    
    public void agregarPlatillo(Platillo platillo) {
        colaPlatillos.agregar(platillo);  // Agregar el platillo a la cola
        mostrarPlatillos();  // Mostrar los platillos actualizados en la tabla
    }


    
   private void eliminarPlatilloPorNombre() {
        String nombre = jtfNombre.getText().trim();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa el nombre del platillo a eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        NodoPlatillo actual = colaPlatillos.getFrente();
        NodoPlatillo anterior = null;
        boolean encontrado = false;

        while (actual != null) {
            if (actual.getPlatillo().getNombre().equalsIgnoreCase(nombre)) {
                encontrado = true;
                if (anterior == null) { 
                    colaPlatillos.setFrente(actual.getSiguiente()); 
                } else { 
                    anterior.setSiguiente(actual.getSiguiente());
                }
                if (actual == colaPlatillos.getFin()) { 
                    colaPlatillos.setFin(anterior); 
                }
                break;
            }
            anterior = actual;
            actual = actual.getSiguiente();
        }

        if (encontrado) {
            JOptionPane.showMessageDialog(this, "Platillo eliminado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            mostrarPlatillos(); 
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró un platillo con ese nombre.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    public void setFrente(NodoPlatillo nodo) {
        this.colaPlatillos.setFrente(nodo);
    }

  
    public void setFin(NodoPlatillo nodo) {
        this.colaPlatillos.setFin(nodo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlatillo = new javax.swing.JTable();
        jbtEliminar = new javax.swing.JButton();
        jbtRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTablePlatillo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Categoria", "Precio", "HorarioDis", "EstaEnStock", "Img"
            }
        ));
        jScrollPane1.setViewportView(jTablePlatillo);

        jbtEliminar.setText("Eliminar");
        jbtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEliminarActionPerformed(evt);
            }
        });

        jbtRegresar.setText("Regresar");
        jbtRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRegresarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jbtEliminar)
                        .addGap(162, 162, 162)
                        .addComponent(jbtRegresar)
                        .addGap(158, 158, 158))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtEliminar)
                    .addComponent(jbtRegresar)
                    .addComponent(jLabel1)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEliminarActionPerformed
        eliminarPlatilloPorNombre();
    }//GEN-LAST:event_jbtEliminarActionPerformed

    private void jbtRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRegresarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jbtRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePlatillo;
    private javax.swing.JButton jbtEliminar;
    private javax.swing.JButton jbtRegresar;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
