/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package PRINCIPAL;

import javax.swing.JOptionPane;
import Clases.*;

import java.awt.Graphics;
import java.awt.Image;

import javax.swing.ImageIcon;
import javax.swing.JPanel;
/**
 *
 * @author karol
 */
public class frmRegistroEmpleados extends javax.swing.JInternalFrame {
private ListaEnlazada listaUsuarios;
FondoPanel fondo = new FondoPanel();
    /**
     * Creates new form frmRegistroEmpleados
     */
    public frmRegistroEmpleados(ListaEnlazada listaUsuarios) {
        this.setContentPane(fondo);
        initComponents();
        this.listaUsuarios = listaUsuarios;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Horario = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        rbMatutino = new javax.swing.JRadioButton();
        rbVespertino = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jlbDescanso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jlbNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jlbUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jlbContraseña = new javax.swing.JTextField();
        jbnAgregar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Registro de empleados");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tipo de empleado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jcbTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mesero", "Cocinero", "Bartender" }));
        jcbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoActionPerformed(evt);
            }
        });
        getContentPane().add(jcbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 230, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Horario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        Horario.add(rbMatutino);
        rbMatutino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbMatutino.setText("Matutino");
        rbMatutino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMatutinoActionPerformed(evt);
            }
        });
        getContentPane().add(rbMatutino, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        Horario.add(rbVespertino);
        rbVespertino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbVespertino.setText("Vespertino");
        rbVespertino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVespertinoActionPerformed(evt);
            }
        });
        getContentPane().add(rbVespertino, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Dia de descanso");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jlbDescanso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbDescanso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlbDescansoActionPerformed(evt);
            }
        });
        getContentPane().add(jlbDescanso, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 230, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jlbNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlbNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jlbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 230, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Usuario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jlbUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlbUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jlbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 230, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Contraseña");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jlbContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlbContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(jlbContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 230, -1));

        jbnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbnAgregar.setText("Agregar");
        jbnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jbnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTipoActionPerformed

    private void rbMatutinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMatutinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMatutinoActionPerformed

    private void rbVespertinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVespertinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbVespertinoActionPerformed

    private void jlbDescansoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlbDescansoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbDescansoActionPerformed

    private void jlbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlbNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbNombreActionPerformed

    private void jlbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlbUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbUsuarioActionPerformed

    private void jlbContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlbContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbContraseñaActionPerformed

    private void jbnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnAgregarActionPerformed
        String nombre = jlbNombre.getText();
        String tipo = (String) jcbTipo.getSelectedItem();
        String diaDescanso = jlbDescanso.getText();
        String horario;
                if (rbMatutino.isSelected()) {
                    horario = "Matutino";
                } else if (rbVespertino.isSelected()) {
                    horario = "Vespertino";
                } else {
                    horario = "No seleccionado";
                }
         String usuario = jlbUsuario.getText();
         String contraseña = jlbContraseña.getText();


        if (tipo.isEmpty() || nombre.isEmpty() || usuario.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor asegúrate de no dejar ningún espacio en blanco", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Horario nuevoHorario = new Horario(horario, diaDescanso);
            // Crea el nuevo usuario
            Usuario nuevoUsuario = new Usuario(nombre, contraseña, usuario, tipo, true, nuevoHorario);
            listaUsuarios.agregar(nuevoUsuario); // Agrega el nuevo usuario a la lista
            JOptionPane.showMessageDialog(null, "Empleado agregado correctamente");
            jlbNombre.setText("");
            jlbUsuario.setText("");
            jlbContraseña.setText("");
            jlbDescanso.setText("");
        }
    }//GEN-LAST:event_jbnAgregarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Horario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbnAgregar;
    private javax.swing.JComboBox<String> jcbTipo;
    private javax.swing.JTextField jlbContraseña;
    private javax.swing.JTextField jlbDescanso;
    private javax.swing.JTextField jlbNombre;
    private javax.swing.JTextField jlbUsuario;
    private javax.swing.JRadioButton rbMatutino;
    private javax.swing.JRadioButton rbVespertino;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/imagenes/file.png")).getImage();
            
            g.drawImage(imagen,0, 0, getWidth(), getHeight(),this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }

}
