/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package COLAS;

/**
 *
 * @author JorgeBrayham
 */
public class jdCOLAS extends javax.swing.JDialog {

    /**
     * Creates new form jdCOLAS
     */
       metodologia m = new metodologia();
    public jdCOLAS(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbnelemento = new javax.swing.JLabel();
        lbprime = new javax.swing.JLabel();
        btnvaciar = new javax.swing.JButton();
        lbultimo = new javax.swing.JLabel();
        btnpop = new javax.swing.JButton();
        btnpush = new javax.swing.JButton();
        txtvalores = new javax.swing.JTextField();
        Introduce = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbvacia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        lbllena = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnvaciar.setText("Vaciar");
        btnvaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvaciarActionPerformed(evt);
            }
        });

        btnpop.setText("Desencola");
        btnpop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpopActionPerformed(evt);
            }
        });

        btnpush.setText("Encola");
        btnpush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpushActionPerformed(evt);
            }
        });

        Introduce.setText("Ingrese");

        jLabel6.setText("Vacia");

        txtarea.setColumns(20);
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        jLabel4.setText("N elementos");

        jLabel5.setText("LLena");

        jLabel2.setText("Primero");

        jLabel3.setText("Ultimo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Introduce)
                        .addGap(28, 28, 28)
                        .addComponent(txtvalores, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbprime)
                                    .addComponent(lbultimo)
                                    .addComponent(lbnelemento)
                                    .addComponent(lbllena)
                                    .addComponent(lbvacia)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnpush, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnpop)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnvaciar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Introduce)
                            .addComponent(txtvalores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnpush)
                            .addComponent(btnpop)
                            .addComponent(btnvaciar))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbprime)
                                .addGap(18, 18, 18)
                                .addComponent(lbultimo)
                                .addGap(18, 18, 18)
                                .addComponent(lbnelemento)
                                .addGap(18, 18, 18)
                                .addComponent(lbllena)
                                .addGap(18, 18, 18)
                                .addComponent(lbvacia)))))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvaciarActionPerformed
        // TODO add your handling code here:

        if(!txtvalores.getText().equals("")){
            m.VaciarCola();

            lbprime.setText("");
            lbultimo.setText("");
            lbnelemento.setText("");
            lbllena.setText("");
            lbvacia.setText("");
            act();
        }

    }//GEN-LAST:event_btnvaciarActionPerformed

    private void btnpopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpopActionPerformed
        // TODO add your handling code here:

        if(txtvalores.getText().equals("")&& !txtarea.getText().equals("")){
            m.Pop();
           
            lbllena.setText(m.EstaLLena());
            lbvacia.setText(m.EstaVacia());
            act();
             txtvalores.requestFocus();
            txtvalores.setText("");
            
        }

    }//GEN-LAST:event_btnpopActionPerformed

    private void btnpushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpushActionPerformed
        // TODO add your handling code here:

        if(!txtvalores.getText().equals("")){
            m.Push(txtvalores.getText());
            lbllena.setText(m.EstaLLena());
            lbvacia.setText(m.EstaVacia());
            act();
            txtvalores.requestFocus();
            txtvalores.setText("");
        }

    }//GEN-LAST:event_btnpushActionPerformed

       public void act(){
        txtarea.setText(m.VerCola());
        
        lbprime.setText( m.Primero());
        lbultimo.setText( m.Ultimo());
        lbnelemento.setText( m.Elementos());     
    }
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdCOLAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdCOLAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdCOLAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdCOLAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Introduce;
    private javax.swing.JButton btnpop;
    private javax.swing.JButton btnpush;
    private javax.swing.JButton btnvaciar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbllena;
    private javax.swing.JLabel lbnelemento;
    private javax.swing.JLabel lbprime;
    private javax.swing.JLabel lbultimo;
    private javax.swing.JLabel lbvacia;
    private javax.swing.JTextArea txtarea;
    private javax.swing.JTextField txtvalores;
    // End of variables declaration//GEN-END:variables
}
