/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package PRINCIPAL;
import Clases.*;
import Clases1.Cola;
import Clases1.DatosCompartidos;
import Clases1.Ordenes;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author preci
 */
public class frmMCancelaciones extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo;
    public static String nombreMesero; 
    /**
     * Creates new form frmMCancelaciones
     */
    public frmMCancelaciones() {
        initComponents();
        
         this.modelo = new DefaultTableModel();
        TablaCancelaciones.setModel(modelo);

        // Configurar columnas de la tabla
        modelo.addColumn("Nombre");
        modelo.addColumn("Fecha");
        modelo.addColumn("Total");
        modelo.addColumn("Motivo");
        modelo.addColumn("Folio");

        // Cargar datos iniciales
        cargarDatos();
    }
    
 private void cargarDatos() {
    modelo.setRowCount(0); // Limpiar la tabla

    Cola<Ordenes> tempCola = new Cola<>(); 
    while (!DatosCompartidos.cancelaciones.estaVacia()) {
        Ordenes ordenCancelada = DatosCompartidos.cancelaciones.desencolar();

        modelo.addRow(new Object[]{
            
            frmInicio.nombreMesero,
            java.time.LocalDate.now().toString(),
            ordenCancelada.getTotalCuenta(),
            ordenCancelada.getMotivo() != null ? ordenCancelada.getMotivo() : "Motivo no definido",
            ordenCancelada.getFolio()
        });

        tempCola.encolar(ordenCancelada); // Restaurar en la cola temporal
    }

    // Restaurar los datos en la cola original
    while (!tempCola.estaVacia()) {
        DatosCompartidos.cancelaciones.encolar(tempCola.desencolar());
    }
}


   
   private void buscarPorFolio() {
    String folioStr = jlbFolio.getText();

    if (folioStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa un folio.");
        return;
    }

    try {
        int folio = Integer.parseInt(folioStr);
        modelo.setRowCount(0); // Limpiar la tabla

        Cola<Ordenes> tempCola = new Cola<>();
        boolean encontrado = false;

        while (!DatosCompartidos.cancelaciones.estaVacia()) {
            Ordenes ordenCancelada = DatosCompartidos.cancelaciones.desencolar();
            if (ordenCancelada.getFolio() == folio) {
                modelo.addRow(new Object[]{
                    ordenCancelada.getUsuario() != null ? ordenCancelada.getUsuario().getNombre() : "",
                    java.time.LocalDate.now().toString(),
                    ordenCancelada.getTotalCuenta(),
                    ordenCancelada.getMotivo() != null ? ordenCancelada.getMotivo() : "Motivo no definido",
                    ordenCancelada.getFolio()
                });
                encontrado = true;
            }
            tempCola.encolar(ordenCancelada);
        }

        // Restaurar los datos en la cola original
        while (!tempCola.estaVacia()) {
            DatosCompartidos.cancelaciones.encolar(tempCola.desencolar());
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "No se encontró ninguna cancelación con el folio ingresado.");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa un número válido para el folio.");
    }
}




    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCancelaciones = new javax.swing.JTable();
        jlbTitulo = new javax.swing.JLabel();
        jlbFolio = new javax.swing.JTextField();
        jbnRegresar = new javax.swing.JButton();
        jlbBusqueda1 = new javax.swing.JLabel();
        jbnBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        TablaCancelaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaCancelaciones);

        jlbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlbTitulo.setText("Cancelaciones");

        jlbFolio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlbFolioActionPerformed(evt);
            }
        });

        jbnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbnRegresar.setText("Regresar");
        jbnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnRegresarActionPerformed(evt);
            }
        });

        jlbBusqueda1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbBusqueda1.setText("No. Folio");

        jbnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbnBuscar.setText("Buscar");
        jbnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(350, 350, 350)
                            .addComponent(jlbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jlbBusqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jlbFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(470, 470, 470)
                            .addComponent(jbnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jlbTitulo)
                    .addGap(8, 8, 8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlbBusqueda1)
                            .addGap(15, 15, 15)
                            .addComponent(jlbFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9)
                            .addComponent(jbnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addComponent(jbnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlbFolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbFolioActionPerformed

    private void jbnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnRegresarActionPerformed
    this.dispose();
    }//GEN-LAST:event_jbnRegresarActionPerformed

    private void jbnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnBuscarActionPerformed
        buscarPorFolio();
    }//GEN-LAST:event_jbnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCancelaciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbnBuscar;
    private javax.swing.JButton jbnRegresar;
    private javax.swing.JLabel jlbBusqueda1;
    private javax.swing.JTextField jlbFolio;
    private javax.swing.JLabel jlbTitulo;
    // End of variables declaration//GEN-END:variables

   
}
